@apiUrl = http://localhost:8080/boards
@token =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidGFza2luZXNlZUBhcmNhZGEuZmkiLCJuYW1lIjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTc1ODcyNjgyMywiZXhwIjoxNzYxMzE4ODIzfQ.LCWF-QjtZ2BiBfOdtCH8OZJl37LSL8NlhrJh3ZkEIVs

### Get all boards for logged-in user
GET {{apiUrl}}
Authorization: Bearer {{token}}

###

### Create a new board
POST {{apiUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Ruubens board"
}

###

### Delete a board by ID (replace 1 with the actual board id)
DELETE {{apiUrl}}/1
Authorization: Bearer {{token}}
