@apiURL = http://localhost:8080/users

@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6Impvcm1hQGdtYWlsLmNvbSIsIm5hbWUiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU4ODcwMzkyLCJleHAiOjE3NjE0NjIzOTJ9.VJKWy7_bBzRpxAB-SoAj-s0mkf_vTbDqiIT1SFtp66c
GET {{apiURL}}
Authorization: Bearer {{token}}


### Logga in
POST {{apiURL}}/login
Content-Type: application/json

{ 
    "email": "jorma@gmail.com", 
    "password": "Morjens" 
}

### Skapa ny användare
POST {{apiURL}}
Content-Type: application/json

{ 
    "email": "moi@arcada.fi", 
    "password": "Password12" 
}

###
DELETE {{apiURL}}/6
Authorization: Bearer {{token}}